import type { Metadata } from 'next'

import { PagesLayout } from '@/components/layouts/PagesLayout'

import './globalStyles/normalize.css'
import './globalStyles/globals.css'
import './globalStyles/slick.css'
import './globalStyles/slick-theme.css'
import './globalStyles/header.css'
import './globalStyles/header-profile.css'
import './globalStyles/menu.css'
import './globalStyles/catalog-menu.css'
import './globalStyles/navbar-mobile.css'
import './globalStyles/search-modal.css'
import './globalStyles/cart-popup.css'
import './globalStyles/footer.css'
import './globalStyles/auth-popup.css'

export const metadata: Metadata = {
  title: 'Rostelecom store',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return <PagesLayout>{children}</PagesLayout>
}
